spreadsheet = [xlsread('data/treeinfo2.xlsx','img/trees1.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees2.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees3.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees4.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees5.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees6.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees7.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees8.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees9.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees10.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees11.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees12.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees13.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees14.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees15.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees16.png','B3:BX29').'].';
