spreadsheet = [xlsread('data/treeinfo2.xlsx','img/trees01.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees02.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees03.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees04.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees05.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees06.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees07.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees08.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees09.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees10.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees11.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees12.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees13.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees14.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees15.png','B3:BX29').',
    xlsread('data/treeinfo2.xlsx','img/trees16.png','B3:BX29').'].';
